Repository iamprovidence/Software-Design, pull requests merged in 2019-04, with the labels that each got.

#28 Implement UnitOfWork close#26
  Apartments_io/Apartments_io/Apartments_io.csproj
  Apartments_io/Core/Core.csproj
  Apartments_io/DataAccess.Tests/ContextTest/UnitOfWorkTest.cs
  Apartments_io/DataAccess.Tests/DataAccess.Tests.csproj
  Apartments_io/DataAccess.Tests/UnitTest1.cs
  Apartments_io/DataAccess/Context/DataBaseContext.cs
  Apartments_io/DataAccess/Context/UnitOfWork.cs
  Apartments_io/DataAccess/DataAccess.csproj
  Apartments_io/DataAccess/Entities/Bill.cs
  Apartments_io/DataAccess/Interfaces/IUnitOfWork.cs
  Apartments_io/DataAccess/Repositories/GenericRepository.cs
Labels: aim

#29 set up and configure entities. close#17
  Apartments_io/ConsoleTest/ConsoleTest.csproj
  Apartments_io/ConsoleTest/Program.cs
  Apartments_io/DataAccess/Configuration/ApartmentConfiguration.cs
  Apartments_io/DataAccess/Configuration/BillConfiguration.cs
  Apartments_io/DataAccess/Configuration/NotificationConfiguration.cs
  Apartments_io/DataAccess/Configuration/RequestConfiguration.cs
  Apartments_io/DataAccess/Configuration/UserConfiguration.cs
  Apartments_io/DataAccess/Context/DataBaseContext.cs
  Apartments_io/DataAccess/DataAccess.csproj
  Apartments_io/DataAccess/Entities/Apartment.cs
  Apartments_io/DataAccess/Entities/Bill.cs
  Apartments_io/DataAccess/Entities/EntityBase.cs
  Apartments_io/DataAccess/Entities/Notification.cs
  Apartments_io/DataAccess/Entities/Request.cs
  Apartments_io/DataAccess/Entities/User.cs
  Apartments_io/DataAccess/Enums/EmergencyLevel.cs
  Apartments_io/DataAccess/Enums/PaymentStatus.cs
  Apartments_io/DataAccess/Enums/Role.cs
Labels: aim

#31 add generic repository close#18
  Apartments_io/DataAccess/Repositories/GenericRepository.cs
Labels: aim

#33 Feature/data base and infrastructure
  Apartments_io/Apartments_io/Controllers/HomeController.cs
  Apartments_io/Apartments_io/Startup.cs
  Apartments_io/Apartments_io/Views/Home/Index.cshtml
  Apartments_io/Apartments_io/appsettings.json
  Apartments_io/Core/Configuration/DbEntityConfiguration.cs
  Apartments_io/DataAccess/Configuration/ApartmentConfiguration.cs
  Apartments_io/DataAccess/Configuration/NotificationConfiguration.cs
  Apartments_io/DataAccess/Configuration/UserConfiguration.cs
  Apartments_io/DataAccess/Context/DataBaseContext.cs
  Apartments_io/DataAccess/Context/UnitOfWork.cs
  Apartments_io/DataAccess/Entities/Notification.cs
  Apartments_io/DataAccess/Infrastructure/AspInfrastructure.cs
  Apartments_io/DataAccess/Interfaces/IDbContextSettable.cs
  Apartments_io/DataAccess/Interfaces/IRepository.cs
  Apartments_io/DataAccess/Interfaces/IUnitOfWork.cs
  Apartments_io/DataAccess/Migrations/20190402181442_Init.Designer.cs
  Apartments_io/DataAccess/Migrations/20190402181442_Init.cs
  Apartments_io/DataAccess/Migrations/DataBaseContextModelSnapshot.cs
  Apartments_io/DataAccess/Repositories/GenericRepository.cs
Labels: aim, bug fix

#41 Add admin page markup, close#16
  Frontend/areas/administrator/index.html
  Frontend/css/index.css
Labels: aim, design

#39 Add administrator controllers close#22
  Apartments_io/Apartments_io/Apartments_io.csproj
  Apartments_io/Apartments_io/Areas/Administrator/Controllers/AdminPagesController.cs
  Apartments_io/Apartments_io/Areas/Administrator/Views/AdminPages/Index.cshtml
  Apartments_io/Apartments_io/Areas/Administrator/Views/_ViewImports.cshtml
  Apartments_io/Apartments_io/Controllers/HomeController.cs
  Apartments_io/Apartments_io/Startup.cs
  Apartments_io/Apartments_io/Views/Home/Index.cshtml
  Apartments_io/DataAccess/Infrastructure/AspInfrastructure.cs
  Apartments_io/DataAccess/Interfaces/IDbContextSettable.cs
  Apartments_io/DataAccess/Interfaces/IRepository.cs
  Apartments_io/DataAccess/Repositories/GenericRepository.cs
Labels: aim

#43 add Layout
  Apartments_io/Apartments_io/Areas/Administrator/Controllers/AdminPagesController.cs
  Apartments_io/Apartments_io/Areas/Administrator/Views/AdminPages/Index.cshtml
  Apartments_io/Apartments_io/Areas/Administrator/Views/Shared/_Layout.cshtml
  Apartments_io/Apartments_io/wwwroot/css/Administrator/index.css
  Apartments_io/Apartments_io/wwwroot/lib/bootstrap/css/bootstrap.min.css
  Apartments_io/Apartments_io/wwwroot/lib/bootstrap/js/bootstrap.min.js
Labels: aim

#44 Add "Create" button
  Apartments_io/Apartments_io/Areas/Administrator/Views/AdminPages/Index.cshtml
  Apartments_io/Apartments_io/Areas/Administrator/Views/Shared/_Layout.cshtml
  Apartments_io/Apartments_io/wwwroot/css/Administrator/index.css
  Apartments_io/Apartments_io/wwwroot/js/jquery-3.3.1.min.js
  Frontend/areas/administrator/index.html
  Frontend/css/index.css
Labels: design, enhancement
